#!/usr/bin/env bash
# Lists every image asset under site/src/content/films/ that is still a
# 1x1 placeholder (the build-time stand-ins generated by the implementation
# plan). Use this to track what assets still need to be replaced with real
# imagery before launch.
#
# Usage:
#   ./scripts/check-placeholders.sh         # prints a one-line summary + list
#   ./scripts/check-placeholders.sh --all   # prints status for every image

set -euo pipefail

cd "$(dirname "$0")/.."

ALL=false
[[ "${1:-}" == "--all" ]] && ALL=true

placeholders=()
real=()

while IFS= read -r f; do
  # 1x1 JPEG placeholders are 285 bytes; 1x1 PNG placeholders are 70 bytes.
  size=$(wc -c < "$f" | tr -d ' ')
  if [[ "$size" -le 300 ]]; then
    placeholders+=("$f")
  else
    real+=("$f")
  fi
done < <(find site/src/content/films -type f \( -name '*.jpg' -o -name '*.png' \) | sort)

if $ALL; then
  echo "=== Real assets (${#real[@]}) ==="
  for f in "${real[@]}"; do
    size=$(wc -c < "$f" | tr -d ' ')
    printf "  %-7s  %s\n" "${size}B" "$f"
  done
fi

echo "=== Placeholder assets (${#placeholders[@]}) ==="
for f in "${placeholders[@]}"; do
  printf "  ✗ %s\n" "$f"
done

echo
echo "Summary: ${#placeholders[@]} placeholder, ${#real[@]} real (of $((${#placeholders[@]} + ${#real[@]})) total)."

if [[ ${#placeholders[@]} -eq 0 ]]; then
  echo "All assets replaced. ✅"
fi
